// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjgCqFBAOzhIMa0AGoT0vpRGg1qWYwh8',
    appId: '1:223810171939:web:15f9e62bb228e0919fad96',
    messagingSenderId: '223810171939',
    projectId: 'doc-circle',
    authDomain: 'doc-circle.firebaseapp.com',
    storageBucket: 'doc-circle.firebasestorage.app',
    measurementId: 'G-4T076JFZNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojKQ_Wps9a2r8yJ8heau54DZe7Lcv6kw',
    appId: '1:223810171939:android:78b1996c626e029c9fad96',
    messagingSenderId: '223810171939',
    projectId: 'doc-circle',
    storageBucket: 'doc-circle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SnPd2opuzArEzb4cCpS5c8ZzNQUFcU0',
    appId: '1:223810171939:ios:506a43bf686437e49fad96',
    messagingSenderId: '223810171939',
    projectId: 'doc-circle',
    storageBucket: 'doc-circle.firebasestorage.app',
    iosClientId: '223810171939-v5k3bd98fgqh53h64e8pi9k74b98vmq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.medcon',
  );
}
